#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Normalize badly-collapsed Markdown generated by older project-collection batches.

This is a conservative structural repair pass:
- inserts newlines before known section markers
- promotes section labels to Markdown headings
- restores list/table-ish readability where safe
- does NOT pretend to deepen research; quality_audit.py remains the gatekeeper
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SECTION_MAP = [
    ("📌 一句话定位", "## 📌 一句话定位"),
    ("🏗️ 项目全景", "## 🏗️ 项目全景"),
    ("🧠 核心架构", "## 🧠 核心架构"),
    ("🔍 源码深度解读", "## 🔍 源码深度解读"),
    ("🌐 社区口碑", "## 🌐 社区口碑"),
    ("🌐 全网口碑画像", "## 🌐 全网口碑画像"),
    ("⚔️ 竞品对比", "## ⚔️ 竞品对比"),
    ("🎯 核心研判", "## 🎯 核心研判"),
    ("📂 关键文件路径速查", "## 📂 关键文件路径速查"),
    ("⭐ 三条关键发现", "## ⭐ 三条关键发现"),
    ("🧪 研究方法与数据来源", "## 🧪 研究方法与数据来源"),
    ("关键文件精读", "### 关键文件精读"),
    ("关键逻辑总结", "### 关键逻辑总结"),
    ("GitHub Issues 抽样", "### GitHub Issues 抽样"),
    ("Pull Requests 抽样", "### Pull Requests 抽样"),
    ("Releases 抽样", "### Releases 抽样"),
    ("真实反馈与维护信号研判", "### 真实反馈与维护信号研判"),
    ("优势", "### 优势"),
    ("风险", "### 风险"),
    ("适用场景", "### 适用场景"),
    ("不适用场景", "### 不适用场景"),
]

FIELD_LABELS = ["仓库", "解决的问题", "基础指标", "Topics", "Homepage", "顶层目录分布（递归树抽样汇总）", "关键文件候选"]


def normalize(text: str) -> str:
    s = text.replace("\r\n", "\n").replace("\r", "\n")

    # If first title is collapsed, promote it.
    s = re.sub(r"^🔬\s*([^#\n]+?)(?=📌|🏗️|🧠|🔍|$)", r"# 🔬 \1\n\n", s)

    for raw, heading in SECTION_MAP:
        s = s.replace(raw, f"\n\n{heading}\n\n")

    for label in FIELD_LABELS:
        s = re.sub(rf"(?<!\n){re.escape(label)}：", f"\n- **{label}**：", s)

    # Common glued prose/list markers.
    s = re.sub(r"(?<!\n)(存在 Python 入口|存在 Node/前端|项目显式提供测试目录|仓库包含 \.github)", r"\n- \1", s)
    s = re.sub(r"(?<!\n)(如果用户只读 README|入口文件决定外部交互界面|从关键文件组合看)", r"\n- \1", s)
    s = re.sub(r"(?<!\n)(若外部搜索数据不可用|高频问题通常比 README)", r"\n- \1", s)

    # Split before issue/PR/release bullets.
    s = re.sub(r"(?<!\n)(#\d+ \[(?:OPEN|CLOSED|MERGED)\])", r"\n- \1", s)
    s = re.sub(r"(?<!\n)(PR #\d+ \[(?:OPEN|CLOSED|MERGED)\])", r"\n- \1", s)
    s = re.sub(r"(?<!\n)(v\d[^（\n]{0,40}（published=)", r"\n- \1", s)

    # Split key file list at file-like tokens when they were glued.
    s = re.sub(r"(?<![`\n])((?:README|CLAUDE|CONTRIBUTING)\.md|package\.json|pyproject\.toml|requirements\.txt|go\.mod|Cargo\.toml|tests/[^\s，。]+)", r"\n- `\1`", s)

    # Avoid overblanking.
    s = re.sub(r"\n{3,}", "\n\n", s)
    return s.strip() + "\n"


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("Usage: normalize_markdown.py <file> [<file> ...]", file=sys.stderr)
        return 2
    for arg in argv[1:]:
        p = Path(arg)
        if not p.is_absolute():
            p = ROOT / p
        original = p.read_text(encoding="utf-8")
        fixed = normalize(original)
        if fixed != original:
            p.write_text(fixed, encoding="utf-8", newline="\n")
            print(f"normalized {p.relative_to(ROOT)}")
        else:
            print(f"unchanged {p.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
